project_id = "ysxlvwxwlljxtjncwtjh"

[functions.chat]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.award-weekly-badges]
verify_jwt = false

[functions.snapshot-leaderboard]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.phone-login]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false

[functions.phone-signup]
verify_jwt = false
